### ISSUE TITLE
Why was the pricing data forked into another subgraph?

### ISSUE THREAD

**Issue by ebadiere** [sushiswap/sushiswap-subgraph#15]
I was assigned this graph project as a curator for thegraph.  As a curator I would like to know why the pricing data was forked into another subgraph?  What's the purpose of a subgraph that only supports MasterChef and MasterChefPool data?

I was hoping to use this subgraph and perhaps the uniswap subgraph to identify pairs with enough liquidity for arbitrage opportunities with minimal slippage.

Apologies if this is not the correct place to ask this question.

**Comment by matthewlilley** [comment]
Hey @ebadiere,

> As a curator I would like to know why the pricing data was forked into another subgraph?

I think the pricing data you mention if part of the exchange subgraph which will shortly be merged into this repository, but as an independent subgraph like the others.

> What's the purpose of a subgraph that only supports MasterChef and MasterChefPool data?

The purpose of this subgraph is to provide data related to Master Chef and it's Pools, things like rewards, and other metrics, and also historical data.

**Comment by jiro-ono** [comment]
@ebadiere glad to have as curator for our graph project.

In regards to the forked subgraph, we initially did so due to us forking from uniswap and having to cut corners initially. So we just modified their subgraph to work with our contracts.

Also we have decided to go with the design choice of breaking our stuff up into multiple subgraphs, to help with sync times. Then we eventually envision composing the multiple subgraphs together into one once that becomes a reality.

We also recently merged in a couple of other subgraphs, and we have some major additions planned for the next few weeks where we will add a new subgraph for the exchange data, and will be adding a lot more for the MasterChefPool entity.

Also you can still use the forked subgraph for arbitrage opportunities, you won't need any of the data from MasterChef or MasterChefPool entities.
